project:
  type: book
  output-dir: ../../docs/models_and_data
  execute-dir: project

format:
  html:
    code-fold: true
    code-summary: "Show the code"

# execute:
#   freeze: auto

book:
  title: "Site Comparisons"
  chapters:
    - index.qmd
    - chapters/dmr_rasher_steneck.qmd
    - chapters/farrell_rasher_2026.qmd
    - chapters/godbout_st_lawrence.qmd
    - chapters/gulf_of_maine_ios_southwestern_gom.qmd
